export interface SyzygyColors {
  primary: string;
  onPrimary: string;
  primaryMuted: string;
  primarySubtle: string;
  error: string;
  onError: string;
  errorMuted: string;
  destructive: string;
  onDestructive: string;
  destructiveMuted: string;
  success: string;
  onSuccess: string;
  successMuted: string;
  warning: string;
  onWarning: string;
  warningMuted: string;
  background: string;
  surface: string;
  surfaceSecondary: string;
  surfaceTertiary: string;
  onSurface: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  textDisabled: string;
  textInverse: string;
  border: string;
  separator: string;
  overlay: string;
  scrim: string;
  link: string;
  focus: string;
  secondary: string;
  disabled: string;
  overlayAlpha: number;
}

export const defaultColors: SyzygyColors = {
  primary: '#2563EB',
  onPrimary: '#FFFFFF',
  primaryMuted: '#DBEAFE',
  primarySubtle: '#EFF6FF',
  error: '#DC2626',
  onError: '#FFFFFF',
  errorMuted: '#FEE2E2',
  destructive: '#DC2626',
  onDestructive: '#FFFFFF',
  destructiveMuted: '#FEE2E2',
  success: '#16A34A',
  onSuccess: '#FFFFFF',
  successMuted: '#DCFCE7',
  warning: '#D97706',
  onWarning: '#FFFFFF',
  warningMuted: '#FEF3C7',
  background: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceSecondary: '#F9FAFB',
  surfaceTertiary: '#F3F4F6',
  onSurface: '#111827',
  textPrimary: '#111827',
  textSecondary: '#6B7280',
  textTertiary: '#9CA3AF',
  textDisabled: '#D1D5DB',
  textInverse: '#FFFFFF',
  border: '#E5E7EB',
  separator: '#F3F4F6',
  overlay: '#000000',
  scrim: '#000000',
  link: '#2563EB',
  focus: '#2563EB',
  secondary: '#6B7280',
  disabled: '#D1D5DB',
  overlayAlpha: 0.4,
};

export const darkThemeColors: SyzygyColors = {
  primary: '#3D8BFF',
  onPrimary: '#FFFFFF',
  primaryMuted: '#0F2A54',
  primarySubtle: '#061529',
  error: '#FF6B6B',
  onError: '#FFFFFF',
  errorMuted: '#4A1A1A',
  destructive: '#FF6B6B',
  onDestructive: '#FFFFFF',
  destructiveMuted: '#4A1A1A',
  success: '#4CD964',
  onSuccess: '#FFFFFF',
  successMuted: '#0F3A1E',
  warning: '#FFB840',
  onWarning: '#FFFFFF',
  warningMuted: '#4A330A',
  background: '#000000',
  surface: '#1C1C1E',
  surfaceSecondary: '#2C2C2E',
  surfaceTertiary: '#3A3A3C',
  onSurface: '#F2F2F7',
  textPrimary: '#F2F2F7',
  textSecondary: '#9B9BA1',
  textTertiary: '#6E6E73',
  textDisabled: '#48484A',
  textInverse: '#1C1C1E',
  border: '#38383A',
  separator: '#38383A',
  overlay: '#000000',
  scrim: '#000000',
  link: '#3D8BFF',
  focus: '#3D8BFF',
  secondary: '#9B9BA1',
  disabled: '#3A3A3C',
  overlayAlpha: 0.4,
};

export const highContrastColors: SyzygyColors = {
  primary: '#0047CC',
  onPrimary: '#FFFFFF',
  primaryMuted: '#CCDDFF',
  primarySubtle: '#E5EEFF',
  error: '#B71C1C',
  onError: '#FFFFFF',
  errorMuted: '#FFCDD2',
  destructive: '#B71C1C',
  onDestructive: '#FFFFFF',
  destructiveMuted: '#FFCDD2',
  success: '#1B5E20',
  onSuccess: '#FFFFFF',
  successMuted: '#C8E6C9',
  warning: '#BF360C',
  onWarning: '#FFFFFF',
  warningMuted: '#FFE0B2',
  background: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceSecondary: '#F5F5F5',
  surfaceTertiary: '#EEEEEE',
  onSurface: '#000000',
  textPrimary: '#000000',
  textSecondary: '#000000',
  textTertiary: '#000000',
  textDisabled: '#424242',
  textInverse: '#FFFFFF',
  border: '#000000',
  separator: '#000000',
  overlay: '#000000',
  scrim: '#000000',
  link: '#0047CC',
  focus: '#0047CC',
  secondary: '#424242',
  disabled: '#9E9E9E',
  overlayAlpha: 0.6,
};
