name: CI
on:
  push:
    branches: ['**']
    tags-ignore: ['*']
jobs:
  ci:
    uses: Syzygy-Hub/.github/.github/workflows/rn-ci.yml@main
    with:
      node_version: '20'
      eslint_config: '.eslintrc.json'
